apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b8ywcujd9-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:ec617cfb8e919c715bf275e0c5903fd768aec473@sha256:1e4187fde35a0f8638c10058fd8ea3925de3119c487cb176c5dd4afc65f85766
          name: container-image
